version: '3'
services:
  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - server_data:/app/SERVER_SET
    environment:
      - ENV=development
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  server_data:
