name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Set environment variables
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> $GITHUB_ENV
          echo "AWS_ACCES_KEY=${{ secrets.AWS_ACCES_KEY }}" >> $GITHUB_ENV
          echo "AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "STRIPE_KEY=${{ secrets.STRIPE_KEY }}" >> $GITHUB_ENV
          echo "STRIPE_SECRET=${{ secrets.STRIPE_SECRET }}" >> $GITHUB_ENV
          echo "STRIPE_ENDPOINT_SECRET=${{ secrets.STRIPE_ENDPOINT_SECRET }}" >> $GITHUB_ENV

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no * ubuntu@35.176.103.203:/home/ubuntu/app

      - name: SSH and run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@35.176.103.203 << 'EOF'
          cd /home/ubuntu/app
          sudo docker-compose -f docker-compose.prod.yml down
          sudo docker-compose -f docker-compose.prod.yml up --build -d
          EOF
